"""Prompt helpers for the AI secondaries deal screener."""

from __future__ import annotations

import json

ANALYSIS_SYSTEM_PROMPT = """You are a private equity secondaries analyst assistant.
Create a first-pass screening analysis from messy deal notes.
Be conservative. Do not invent facts. When information is missing, say so clearly.
Return valid JSON only.
Use concise investment language appropriate for a mid-market secondaries fund.
Score all scorecard fields on a 1-5 scale, where 5 is strongest.
"""


JSON_SCHEMA_EXAMPLE = {
    "opportunity_name": "Project Northbridge",
    "one_line_summary": "Single-asset GP-led continuation vehicle for a sticky vertical software asset, with good quality signals but real concentration and pricing questions.",
    "transaction_type": "GP-led continuation vehicle",
    "seller_type": "Existing LPs with a sponsor-led process",
    "manager_sponsor": "Alder Ridge Capital",
    "portfolio_asset": "ComplianceCloud",
    "strategy": "Mid-market buyout / software secondaries",
    "geography": "United States and United Kingdom",
    "vintage_exposure": "2016-vintage fund rolling into a new continuation vehicle",
    "remaining_unfunded_commitments": "No traditional unfunded disclosed; reserve expected inside the continuation vehicle",
    "preliminary_recommendation": "Explore",
    "memo_confidence": "medium",
    "deal_summary": "2-4 sentences summarizing the transaction.",
    "seller_motivation": "1-3 sentences on why the seller is transacting.",
    "portfolio_asset_snapshot": "2-4 sentences on what the buyer is actually getting.",
    "top_exposures": ["bullet", "bullet"],
    "quality_signals": ["bullet", "bullet"],
    "pricing_observations": ["bullet", "bullet"],
    "structuring_considerations": ["bullet", "bullet"],
    "concentration_risks": ["bullet", "bullet"],
    "bull_case": ["bullet", "bullet"],
    "bear_case": ["bullet", "bullet"],
    "red_flags": ["bullet", "bullet"],
    "diligence_questions": ["bullet", "bullet"],
    "analyst_view": "2-4 sentences on what still requires human judgment.",
    "scorecard": {
        "asset_quality": 4,
        "manager_quality": 4,
        "diversification": 2,
        "pricing": 3,
        "downside_protection": 3,
        "overall": 3,
    },
}


MARKDOWN_SYSTEM_PROMPT = """Write a polished markdown memo for a mid-market secondaries interviewer.
Do not mention that the memo was generated by AI except in the final Analyst View section.
Use crisp section headers and short investment prose.
"""



def build_analysis_prompt(*, deal_brief: str, fund_lens: str | None, partner_questions: str | None) -> str:
    """Build the JSON analysis prompt."""
    return f"""
Create a first-pass secondaries screening analysis from the material below.
Focus on transaction type, seller motivation, concentration, pricing support, structuring, diligence gaps, and an initial recommendation.

Important rules:
- Use only facts supported by the input.
- Where data is missing, say that directly.
- Keep lists concise and investment-relevant.
- The recommendation should be one of: Pass, Park, Explore, or Prioritize.
- memo_confidence should be one of: low, medium, high.
- Return JSON only.

Expected JSON shape:
{json.dumps(JSON_SCHEMA_EXAMPLE, indent=2)}

Deal material:
{deal_brief}

Fund lens / mandate:
{fund_lens or 'Not provided.'}

Partner or IC questions to prioritize:
{partner_questions or 'Not provided.'}
""".strip()



def build_markdown_prompt(analysis: dict) -> str:
    """Build the markdown memo prompt from structured analysis."""
    return f"""
{MARKDOWN_SYSTEM_PROMPT}

Using the structured analysis below, write a markdown memo with these sections in order:
1. Title
2. Snapshot
3. Deal Summary
4. Seller Motivation
5. Portfolio / Asset Snapshot
6. Top Exposures
7. Quality Signals
8. Pricing Observations
9. Structuring Considerations
10. Concentration Risks
11. Bull Case
12. Bear Case
13. Red Flags
14. Diligence Questions
15. Scorecard (1-5)
16. Analyst View

Formatting rules:
- Use bullets where appropriate.
- Keep the Snapshot as bullets.
- In the Scorecard section, include each score as a bullet and calculate the average score to two decimals.
- Keep the prose crisp and interviewer-ready.
- Do not fabricate any details beyond the structured analysis.

Structured analysis:
{json.dumps(analysis, indent=2)}
""".strip()
